package com.jftse.emulator.server.core.life.event;

public enum GameEventType {
    ON_TICK,
    ON_LOGIN,
    ON_LOGOUT,

    CHALLENGE_INIT_HP,
    CHALLENGE_DAMAGE,
    CHALLENGE_POINT,
    CHALLENGE_FINISH,

    EMBLEM_INIT,

    ENCHANT_ON_ANNOUNCE,
    ON_ENCHANT,

    GACHA_OPENED,

    RECIPE_COMBINED,
    INVENTORY_ITEM_TIME_EXPIRED,

    ON_PLAYER_ANNOUNCE,
    PLAYER_QUICK_SLOT_USE,

    LOBBY_JOINED,
    LOBBY_LEFT,
    ROOM_LOBBY_JOINED,
    ROOM_CREATED,
    ROOM_JOINED,
    ROOM_LEFT,
    ROOM_POSITION_CHANGED,
    ROOM_MAP_CHANGED,

    MP_RELAY_CONNECTED,
    MP_GAME_ANIM_SKIP_TRIGGERED,
    MP_GAME_ANIM_SKIP_END,
    MP_MATCH_START,
    MP_MATCH_END,
    MP_PLAYER_USE_SKILL,
    MP_PLAYER_PICKING_UP_CRYSTAL,
    MP_PLAYER_HITS_TARGET,
    MP_PLAYER_SWAP_QUICK_SLOT_ITEMS,
    MP_BALL_HIT,

    SHOP_MAINTENANCE_REQUESTED,
    ON_SHOP_LOAD,
    ON_SHOP_LOAD_PREPARE,
    SHOP_ITEM_BOUGHT,

    TUTORIAL_INIT,
    TUTORIAL_FINISH,

    ON_DEV_PACKET,

    SESSION_TIME_UPDATE,

    ON_HEARTBEAT;

    public String getName() {
        return toString();
    }
}
