# Configuration file for the game server

#
# TCP port to reach the game server
ServerPort=5895

#
# Minimum time (milliseconds) between server update ticks
MinServerUpdateTime=1

#
# Time (in seconds) before the server is forced to crash if it is frozen
MaxCoreStuckTime=60

#
# Update server uptime period (in minutes)
UpdateUptimeInterval=10
