INSERT INTO Config (id, description, name, `type`, value) VALUES(1, 'Enables or disables the built-in anticheat (JFTSE exclusive)', 'anticheat.enabled', 'boolean', 'false');
INSERT INTO Config (id, description, name, `type`, value) VALUES(2, 'Port used for the anticheat system (JFTSE exclusive)', 'anticheat.port', 'int', '1337');
INSERT INTO Config (id, description, name, `type`, value) VALUES(3, 'Handles developer/debug packets (Packet ID 0x555)', 'dev.packets.handle', 'boolean', 'false');
INSERT INTO Config (id, description, name, `type`, value) VALUES(4, 'Enables translation of packet IDs', 'packets.id.translate.enabled', 'boolean', 'true');
INSERT INTO Config (id, description, name, `type`, value) VALUES(5, 'Enables logging of all network packets', 'logging.packets.all.enabled', 'boolean', 'true');
INSERT INTO Config (id, description, name, `type`, value) VALUES(6, 'Enables network encryption for secure communication', 'network.encryption.enabled', 'boolean', 'false');
INSERT INTO Config (id, description, name, `type`, value) VALUES(7, 'Encrypts player passwords upon login', 'password.encryption.enabled', 'boolean', 'false');
INSERT INTO Config (id, description, name, `type`, value) VALUES(8, 'Maximum player level (JFTSE exclusive, levels above 65 require client modifications)', 'player.level.max', 'int', '65');
INSERT INTO Config (id, description, name, `type`, value) VALUES(9, 'Minimum required level to change room mode via command', 'command.room.mode.change.player.level', 'int', '60');
INSERT INTO Config (id, description, name, `type`, value) VALUES(10, 'Global gold bonus multiplier (Single Player)', 'game.bonus.global.gold', 'int', '5');
INSERT INTO Config (id, description, name, `type`, value) VALUES(11, 'Global experience bonus multiplier (Single Player)', 'game.bonus.global.exp', 'int', '5');
INSERT INTO Config (id, description, name, `type`, value) VALUES(12, 'Experience bonus for winning a game (Basic & Battle)', 'game.bonus.wongame.exp', 'double', '0.2');
INSERT INTO Config (id, description, name, `type`, value) VALUES(13, 'Gold bonus for winning a game (Basic & Battle)', 'game.bonus.wongame.gold', 'double', '0.2');
INSERT INTO Config (id, description, name, `type`, value) VALUES(14, 'Enables logging of packets in console output', 'logging.packets.console-output.enabled', 'boolean', 'true');
INSERT INTO Config (id, description, name, `type`, value) VALUES(15, 'Multiplier applied to ranking points in Guardian Hard mode', 'matchplay.guardian.hard.won.ranking-point.multiplier', 'double', '1.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(16, 'Allows Snow Moon map in Guardian mode', 'game.map.allow.snowmoon', 'boolean', 'false');
INSERT INTO Config (id, description, name, `type`, value) VALUES(17, 'Maximum number of fish allowed per room', 'fish.spawn.max_per_room', 'int', '10');
INSERT INTO Config (id, description, name, `type`, value) VALUES(18, 'Number of fish to spawn initially per spawn location', 'fish.spawn.count', 'int', '4');
INSERT INTO Config (id, description, name, `type`, value) VALUES(19, 'Timeout for inactive fish before despawning (in minutes)', 'fish.inactivity.timeout', 'int', '10');
INSERT INTO Config (id, description, name, `type`, value) VALUES(20, 'Chance for fish to spawn at a location (in percent)', 'fish.spawn.chance', 'int', '20');
INSERT INTO Config (id, description, name, `type`, value) VALUES(21, 'Minimum time between fish spawns (in seconds)', 'fish.spawn.min_time', 'float', '6.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(22, 'Maximum time between fish spawns (in seconds)', 'fish.spawn.max_time', 'float', '8.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(23, 'Standard swimming speed for fish (variant 1)', 'fish.speed.normal1', 'float', '2.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(24, 'Standard swimming speed for fish (variant 2)', 'fish.speed.normal2', 'float', '3.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(25, 'Speed used by fish when attacking bait', 'fish.speed.attack', 'float', '4.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(26, 'Speed used by fish when frightened', 'fish.speed.scared', 'float', '10.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(27, 'Speed used by fish when disengaging from bait', 'fish.speed.disengage', 'float', '10.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(28, 'Normal turning speed of fish (in degrees)', 'fish.speed.turning.normal', 'float', '3.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(29, 'Turning speed during disengagement (in degrees)', 'fish.speed.turning.disengage', 'float', '6.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(30, 'Chance for a successful bite once bait is reached (in percent)', 'fish.bite.success.chance', 'int', '40');
INSERT INTO Config (id, description, name, `type`, value) VALUES(31, 'Interval between bite attempts (in seconds)', 'fish.bite.attempt.interval', 'float', '2.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(32, 'Attack radius relative to fish length', 'fish.radius.attack', 'float', '4.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(33, 'Distance considered too close to bait to attack (relative to length)', 'fish.radius.bait.too_close', 'float', '6.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(34, 'Radius for detecting frightening stimuli (relative to length)', 'fish.radius.frightened', 'float', '10.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(35, 'Detection radius for bait (relative to fish length)', 'fish.radius.bait.detection', 'float', '10.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(36, 'Maximum distance from spawn point for roaming (5.0 = 1 square)', 'fish.radius.random_position', 'float', '10.0');
INSERT INTO Config (id, description, name, `type`, value) VALUES(37, 'Chance for idle fish to start swimming movement (pattern 1)', 'fish.movement.chance1', 'int', '40');
INSERT INTO Config (id, description, name, `type`, value) VALUES(38, 'Chance for idle fish to start swimming movement (pattern 2)', 'fish.movement.chance2', 'int', '25');