version: "3.9"
services:
  db:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:                                                                      
        NETWORK_IP: '127.0.0.1'  
    depends_on:
      - "db"
    ports:
      - "5894:5894"
      - "5895:5895"
      - "5896:5896"